### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tizzzzy** [8421BCD/DemoRank#1]
Hi,
I am using `python version 3.9`, `CUDA version 12.2`. I installed the required packages in the README. I also changed the `model_name_or_path` to `--model_name_or_path google/flan-t5-xl \` and `CUDA_VISIBLE_DEVICES` to `export CUDA_VISIBLE_DEVICES=1` in `llm_score.sh`. 

However, when I try to run `bash llm_score.sh`, I got this error:
``` bash
(demorank) [conda] [lh599@corfu:DemoRank]$ bash llm_score.sh
[2024-07-25 16:21:40,758] torch.distributed.run: [WARNING]
[2024-07-25 16:21:40,758] torch.distributed.run: [WARNING] *****************************************
[2024-07-25 16:21:40,758] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2024-07-25 16:21:40,758] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 426, in <module>
    main()
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 248, in main
    accelerator = Accelerator()
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/accelerator.py", line 371, in __init__
Traceback (most recent call last):
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 426, in <module>
    self.state = AcceleratorState(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 732, in __init__
    main()
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 248, in main
    Traceback (most recent call last):
PartialState(cpu, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 426, in <module>
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 208, in __init__
    accelerator = Accelerator()
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/accelerator.py", line 371, in __init__
    torch.cuda.set_device(self.device)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
    main()
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 248, in main
    self.state = AcceleratorState(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 732, in __init__
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    accelerator = Accelerator()
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/accelerator.py", line 371, in __init__
    PartialState(cpu, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 208, in __init__
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
    self.state = AcceleratorState(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 732, in __init__
############ iteration_number=1, dataset=msmarco ############
    torch.cuda.set_device(self.device)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
    PartialState(cpu, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 208, in __init__
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch.cuda.set_device(self.device)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 426, in <module>
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 426, in <module>
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 426, in <module>
        main()main()

  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 248, in main
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 248, in main
    main()
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 248, in main
    accelerator = Accelerator()
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/accelerator.py", line 371, in __init__
    accelerator = Accelerator()
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/accelerator.py", line 371, in __init__
    accelerator = Accelerator()
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 732, in __init__
    self.state = AcceleratorState(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 732, in __init__
    self.state = AcceleratorState(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 732, in __init__
    PartialState(cpu, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 208, in __init__
    PartialState(cpu, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 208, in __init__
    PartialState(cpu, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 208, in __init__
    torch.cuda.set_device(self.device)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
    torch.cuda.set_device(self.device)
      File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
torch.cuda.set_device(self.device)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 426, in <module>
    main()
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/DemoRank/llm_score.py", line 248, in main
    accelerator = Accelerator()
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 732, in __init__
    PartialState(cpu, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/accelerate/state.py", line 208, in __init__
    torch.cuda.set_device(self.device)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/cuda/__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████| 2.54k/2.54k [00:00<00:00, 946kB/s]
spiece.model:   0%|                                                                                        | 0.00/792k [00:00<?, ?B/s][2024-07-25 16:21:45,840] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 389515 closing signal SIGTERM
spiece.model: 100%|█████████████████████████████████████████████████████████████████████████████████| 792k/792k [00:02<00:00, 273kB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████| 2.42M/2.42M [00:00<00:00, 24.1MB/s][2024-07-25 16:21:48,460] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 389516) of binary: /research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/bin/python
Traceback (most recent call last):
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/demorank/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
llm_score.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-25_16:21:45
  host      : corfu.cs.rutgers.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 389517)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-25_16:21:45
  host      : corfu.cs.rutgers.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 389518)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-25_16:21:45
  host      : corfu.cs.rutgers.edu
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 389519)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-07-25_16:21:45
  host      : corfu.cs.rutgers.edu
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 389520)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-07-25_16:21:45
  host      : corfu.cs.rutgers.edu
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 389521)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-07-25_16:21:45
  host      : corfu.cs.rutgers.edu
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 389522)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-25_16:21:45
  host      : corfu.cs.rutgers.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 389516)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Can you please take a look?

**Comment by 8421BCD** [comment]
Of course! Please remember to set parameter _nproc_per_node_ in the script (llm_score.sh) to 1 if you are only using one GPU.
